/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IExternalPositionVaultInterface extends ethers.utils.Interface {
  functions: {
    "getExternalPositionLibForType(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getExternalPositionLibForType",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getExternalPositionLibForType",
    data: BytesLike
  ): Result;

  events: {};
}

export class IExternalPositionVault extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IExternalPositionVaultInterface;

  functions: {
    getExternalPositionLibForType(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getExternalPositionLibForType(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  getExternalPositionLibForType(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getExternalPositionLibForType(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getExternalPositionLibForType(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getExternalPositionLibForType(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getExternalPositionLibForType(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExternalPositionLibForType(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getExternalPositionLibForType(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getExternalPositionLibForType(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
