/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IExternalPositionVault } from "./IExternalPositionVault";

export class IExternalPositionVaultFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExternalPositionVault {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IExternalPositionVault;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getExternalPositionLibForType",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
