/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IFreelyTransferableSharesVaultInterface
  extends ethers.utils.Interface {
  functions: {
    "sharesAreFreelyTransferable()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "sharesAreFreelyTransferable",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "sharesAreFreelyTransferable",
    data: BytesLike
  ): Result;

  events: {};
}

export class IFreelyTransferableSharesVault extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IFreelyTransferableSharesVaultInterface;

  functions: {
    sharesAreFreelyTransferable(overrides?: CallOverrides): Promise<{
      sharesAreFreelyTransferable_: boolean;
      0: boolean;
    }>;

    "sharesAreFreelyTransferable()"(overrides?: CallOverrides): Promise<{
      sharesAreFreelyTransferable_: boolean;
      0: boolean;
    }>;
  };

  sharesAreFreelyTransferable(overrides?: CallOverrides): Promise<boolean>;

  "sharesAreFreelyTransferable()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    sharesAreFreelyTransferable(overrides?: CallOverrides): Promise<boolean>;

    "sharesAreFreelyTransferable()"(
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    sharesAreFreelyTransferable(overrides?: CallOverrides): Promise<BigNumber>;

    "sharesAreFreelyTransferable()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    sharesAreFreelyTransferable(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sharesAreFreelyTransferable()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
