/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFreelyTransferableSharesVault } from "./IFreelyTransferableSharesVault";

export class IFreelyTransferableSharesVaultFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFreelyTransferableSharesVault {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IFreelyTransferableSharesVault;
  }
}

const _abi = [
  {
    inputs: [],
    name: "sharesAreFreelyTransferable",
    outputs: [
      {
        internalType: "bool",
        name: "sharesAreFreelyTransferable_",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
