/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IMigratableVault } from "./IMigratableVault";

export class IMigratableVaultFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMigratableVault {
    return new Contract(address, _abi, signerOrProvider) as IMigratableVault;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_who",
        type: "address",
      },
    ],
    name: "canMigrate",
    outputs: [
      {
        internalType: "bool",
        name: "canMigrate_",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_accessor",
        type: "address",
      },
      {
        internalType: "string",
        name: "_fundName",
        type: "string",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_nextAccessor",
        type: "address",
      },
    ],
    name: "setAccessor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_nextVaultLib",
        type: "address",
      },
    ],
    name: "setVaultLib",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
